#!/usr/bin/env python3
"""
apply_patch.py — Apply a patch from scar-results.json to the source tree.

SCAR generates correct patches but does not apply them to disk (by design —
the CRS workflow expects human review before application). This script reads
an accepted patch from scar-results.json and applies it using a context-free
applier that tolerates abbreviated diffs generated by the LLM.

Usage:
    python apply_patch.py --results scar-results.json --repo ~/scarnet/
    python apply_patch.py --results scar-results.json --repo ~/scarnet/ --index 1
    python apply_patch.py --results scar-results.json --repo ~/scarnet/ --dry-run
"""

import argparse
import json
import re
import sys
from pathlib import Path


def _apply_patch_python(source: str, patch: str) -> str | None:
    """Context-free unified diff applier.

    Ignores context lines and locates the changed block by hunk line number
    with a ±20-line search window. Tolerates abbreviated LLM-generated diffs
    whose context lines are hallucinated or missing.
    """
    src_lines = source.splitlines(keepends=True)
    result = list(src_lines)
    offset = 0

    hunk_re = re.compile(r"^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@")

    i = 0
    patch_lines = patch.splitlines(keepends=True)
    while i < len(patch_lines):
        m = hunk_re.match(patch_lines[i])
        if not m:
            i += 1
            continue

        old_start = int(m.group(1)) - 1  # 0-indexed
        i += 1

        removed, added, pre_context = [], [], []
        seen_add = False
        while i < len(patch_lines) and not hunk_re.match(patch_lines[i]):
            line = patch_lines[i]
            if line.startswith("-") and not line.startswith("---"):
                removed.append(line[1:])
                seen_add = False
            elif line.startswith("+") and not line.startswith("+++"):
                added.append(line[1:])
                seen_add = True
            elif not seen_add:
                # context line before the first addition — potential anchor
                pre_context.append(line[1:])
            i += 1

        if not removed and not added:
            continue

        target = old_start + offset

        if removed:
            needle = [l.rstrip() for l in removed]
            search_start = max(0, target - 20)
            search_end = min(len(result), target + 20)
            found_at = None
            for pos in range(search_start, search_end):
                if pos + len(removed) > len(result):
                    break
                window = [result[pos + j].rstrip() for j in range(len(removed))]
                if window == needle:
                    found_at = pos
                    break
            if found_at is None:
                print(f"  ERROR: could not locate removed block near line {old_start + 1}")
                return None
            result[found_at:found_at + len(removed)] = added
            offset += len(added) - len(removed)
        else:
            # Pure insertion: anchor on the last pre-context line so the
            # addition lands immediately after it, not at the raw line number.
            found_at = None
            if pre_context:
                anchor = pre_context[-1].rstrip()
                search_start = max(0, target - 20)
                search_end = min(len(result), target + 20)
                for pos in range(search_start, search_end):
                    if result[pos].rstrip() == anchor:
                        found_at = pos + 1  # insert after the anchor line
                        break
            if found_at is None:
                found_at = min(target, len(result))
            result[found_at:found_at] = added
            offset += len(added)

    return "".join(result)


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Apply a patch from scar-results.json to the source tree",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("--results", metavar="FILE", required=True,
                    help="Path to scar-results.json")
    ap.add_argument("--repo",    metavar="DIR",  required=True,
                    help="Root of the target repository")
    ap.add_argument("--index",   metavar="N", type=int, default=None,
                    help="Index into the results array (default: apply all)")
    ap.add_argument("--all",     action="store_true",
                    help="Apply all patches in the results file (default behaviour when --index omitted)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print the patched file to stdout instead of writing it")
    args = ap.parse_args()

    results_path = Path(args.results)
    repo_root    = Path(args.repo)

    data = json.loads(results_path.read_text())
    if not isinstance(data, list) or len(data) == 0:
        sys.exit("ERROR: results file is empty or not a list")

    indices = [args.index] if args.index is not None else list(range(len(data)))

    ok = 0
    for idx in indices:
        if idx >= len(data):
            print(f"  SKIP: index {idx} out of range")
            continue

        entry   = data[idx]
        patch   = entry.get("patch", "")
        finding = entry.get("finding", {})
        file_path = Path(finding.get("file_path", ""))

        # Strip markdown code fences that LLM sometimes wraps around the diff
        patch = re.sub(r"^```[a-z]*\n?", "", patch, flags=re.MULTILINE)
        patch = re.sub(r"^```\s*$",      "", patch, flags=re.MULTILINE)

        if not patch.strip():
            print(f"  SKIP [{idx}]: patch field is empty")
            continue
        if not file_path.parts:
            print(f"  SKIP [{idx}]: finding has no file_path")
            continue

        # Resolve relative to repo root if the path doesn't exist as-is
        if not file_path.exists():
            candidate = repo_root / file_path
            if candidate.exists():
                file_path = candidate
            else:
                print(f"  SKIP [{idx}]: source file not found: {file_path}")
                continue

        source = file_path.read_text(encoding="utf-8", errors="replace")
        print(f"  [{idx}] Applying patch to {file_path}  (line {finding.get('line', '?')})")

        patched = _apply_patch_python(source, patch)
        if patched is None:
            print(f"  [{idx}] ERROR: patch application failed — skipping")
            continue

        if args.dry_run:
            print(f"\n--- [{idx}] patched output ---")
            print(patched)
        else:
            file_path.write_text(patched, encoding="utf-8")
            print(f"  [{idx}] Written: {file_path}")
        ok += 1

    print(f"\n{ok}/{len(indices)} patch(es) applied{'(dry run)' if args.dry_run else ''}.")


if __name__ == "__main__":
    main()
